# Generated by Django 4.2.7 on 2023-11-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
